import { Document, Folder } from './document-types';

export const MOCK_FOLDERS: Folder[] = [
  { id: 'f1', name: 'Work Documents', color: 'yellow' },
  { id: 'f2', name: 'Personal', color: 'blue' },
  { id: 'f3', name: 'Financials', color: 'green' },
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: 'd1',
    name: 'Q3 Financial Report.pdf',
    type: 'pdf',
    size: '2.4 MB',
    createdAt: '2023-10-15T10:30:00Z',
    isFavorite: true,
    folderId: 'f1',
    inTrash: false,
    isVault: false,
  },
  {
    id: 'd2',
    name: 'Project Proposal.doc',
    type: 'doc',
    size: '1.1 MB',
    createdAt: '2023-10-18T14:20:00Z',
    isFavorite: false,
    folderId: 'f1',
    inTrash: false,
    isVault: false,
  },
  {
    id: 'd3',
    name: 'Vacation Photos.zip',
    type: 'other',
    size: '150 MB',
    createdAt: '2023-09-05T09:15:00Z',
    isFavorite: true,
    folderId: 'f2',
    inTrash: false,
    isVault: false,
  },
  {
    id: 'd4',
    name: 'Tax Returns 2022.pdf',
    type: 'pdf',
    size: '4.5 MB',
    createdAt: '2023-04-10T11:00:00Z',
    isFavorite: false,
    folderId: 'f3',
    inTrash: false,
    isVault: true,
  },
  {
    id: 'd5',
    name: 'Old Resume.doc',
    type: 'doc',
    size: '500 KB',
    createdAt: '2020-01-15T08:00:00Z',
    isFavorite: false,
    folderId: null,
    inTrash: true,
    isVault: false,
  },
  {
    id: 'd6',
    name: 'Product Roadmap Q4.png',
    type: 'image',
    size: '3.2 MB',
    createdAt: '2023-10-20T16:45:00Z',
    isFavorite: false,
    folderId: 'f1',
    inTrash: false,
    isVault: false,
  },
  {
    id: 'd7',
    name: 'Client Presentation.video',
    type: 'video',
    size: '85 MB',
    createdAt: '2023-10-22T09:30:00Z',
    isFavorite: true,
    folderId: 'f1',
    inTrash: false,
    isVault: false,
  },
];
